import React, { useEffect, useMemo, useRef } from 'react'
import { useFrame, useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'
import { clone } from 'three/addons/utils/SkeletonUtils.js'
import * as THREE from 'three'

const HUMAN_HINTS={hips:['hips','pelvis','root'],spine:['spine','chest','torso'],head:['head','neck'],upperArmL:['leftarm','upperarm_l','upperarml','lupperarm','arm_l'],lowerArmL:['leftforearm','lowerarm_l','forearm_l','lforearm'],handL:['lefthand','hand_l','lhand'],upperArmR:['rightarm','upperarm_r','upperarmr','rupperarm','arm_r'],lowerArmR:['rightforearm','lowerarm_r','forearm_r','rforearm'],handR:['righthand','hand_r','rhand'],upperLegL:['leftupleg','thigh_l','upperleg_l','lthigh'],lowerLegL:['leftleg','calf_l','lowerleg_l','lcalf'],footL:['leftfoot','foot_l','lfoot'],upperLegR:['rightupleg','thigh_r','upperleg_r','rthigh'],lowerLegR:['rightleg','calf_r','lowerleg_r','rcalf'],footR:['rightfoot','foot_r','rfoot']}
const CHAINS={handL:['upperArmL','lowerArmL','handL'],handR:['upperArmR','lowerArmR','handR'],footL:['upperLegL','lowerLegL','footL'],footR:['upperLegR','lowerLegR','footR']}
const normalize=(s='')=>String(s).toLowerCase().replace(/[^a-z0-9]/g,'')
export function autoMapBones(bones){const out={};for(const [slot,hints] of Object.entries(HUMAN_HINTS)){const found=bones.find(b=>hints.some(h=>normalize(b.name).includes(normalize(h))));if(found)out[slot]=found.name}return out}
function solveCCD(chain,targetWorld,iterations=5){if(chain.length<2)return;const effector=chain[chain.length-1],jointPos=new THREE.Vector3(),effPos=new THREE.Vector3(),toEff=new THREE.Vector3(),toTarget=new THREE.Vector3(),invParent=new THREE.Quaternion(),deltaWorld=new THREE.Quaternion(),deltaLocal=new THREE.Quaternion(),parentWorld=new THREE.Quaternion();for(let it=0;it<iterations;it++){for(let i=chain.length-2;i>=0;i--){const joint=chain[i];joint.updateWorldMatrix(true,false);effector.updateWorldMatrix(true,false);joint.getWorldPosition(jointPos);effector.getWorldPosition(effPos);toEff.copy(effPos).sub(jointPos).normalize();toTarget.copy(targetWorld).sub(jointPos).normalize();if(toEff.lengthSq()<1e-8||toTarget.lengthSq()<1e-8)continue;deltaWorld.setFromUnitVectors(toEff,toTarget);if(joint.parent){joint.parent.getWorldQuaternion(parentWorld);invParent.copy(parentWorld).invert();deltaLocal.copy(invParent).multiply(deltaWorld).multiply(parentWorld)}else deltaLocal.copy(deltaWorld);joint.quaternion.premultiply(deltaLocal).normalize();joint.updateMatrixWorld(true)}}}
function Marker({bone,active,onSelect}){const ref=useRef(),p=useMemo(()=>new THREE.Vector3(),[]);useFrame(()=>{if(ref.current&&bone){bone.getWorldPosition(p);ref.current.position.copy(p)}});return <mesh ref={ref} onClick={e=>{e.stopPropagation();onSelect?.(bone.name)}}><sphereGeometry args={[active?.035:.022,10,10]}/><meshBasicMaterial color={active?'#ffbe63':'#5f6b80'} depthTest={false}/></mesh>}
function IKTarget({name,position,active,onSelect}){return <mesh position={position} onClick={e=>{e.stopPropagation();onSelect?.(name)}}><sphereGeometry args={[active?.06:.04,14,14]}/><meshStandardMaterial color={active?'#72e2ff':'#43506a'} emissive={active?'#164c59':'#000'} emissiveIntensity={1.4}/></mesh>}
function AttachedAsset({asset,bone}){const gltf=useLoader(GLTFLoader,asset.url);const object=useMemo(()=>clone(gltf.scene),[gltf.scene]);useEffect(()=>{if(!bone)return;bone.add(object);return()=>bone.remove(object)},[bone,object]);useEffect(()=>{object.position.fromArray(asset.position||[0,0,0]);const d=Math.PI/180;const r=asset.rotation||[0,0,0];object.rotation.set((r[0]||0)*d,(r[1]||0)*d,(r[2]||0)*d);object.scale.setScalar(asset.scale||1);object.visible=asset.visible!==false;object.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}})},[object,asset.position,asset.rotation,asset.scale,asset.visible]);return null}

export default function ImportedAvatar({url,onReady,selectedBoneName,rotationDeg,mapping={},onSelectBone,showBones=true,ikEnabled=false,ikTargets={},selectedIK,onSelectIK,onIKMove,morphValues={},materialConfig={},assets=[],exportYaw=0}){
 const gltf=useLoader(GLTFLoader,url),scene=useMemo(()=>clone(gltf.scene),[gltf.scene]),bones=useMemo(()=>{const arr=[];scene.traverse(o=>{if(o.isBone)arr.push(o)});return arr},[scene]),boneByName=useMemo(()=>Object.fromEntries(bones.map(b=>[b.name,b])),[bones])
 const morphEntries=useMemo(()=>{const seen=new Set(),out=[];scene.traverse(o=>{if(!o.isMesh||!o.morphTargetDictionary)return;for(const [name,index] of Object.entries(o.morphTargetDictionary)){if(!seen.has(name)){seen.add(name);out.push({name,index})}}});return out},[scene])
 const materials=useMemo(()=>{const out=[];scene.traverse(o=>{if(o.isMesh&&o.material){const list=Array.isArray(o.material)?o.material:[o.material];list.forEach(m=>{if(!out.some(x=>x.uuid===m.uuid))out.push({uuid:m.uuid,name:m.name||o.name||'Material'})})}});return out},[scene])
 useEffect(()=>{scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});const autoMap=autoMapBones(bones),initialIK={};scene.updateMatrixWorld(true);for(const key of Object.keys(CHAINS)){const bone=boneByName[mapping[key]||autoMap[key]];if(bone){const p=new THREE.Vector3();bone.getWorldPosition(p);initialIK[key]=p.toArray()}}onReady?.({bones:bones.map(b=>({name:b.name,uuid:b.uuid})),autoMap,hasRig:bones.length>0,initialIK,morphs:morphEntries.map(x=>x.name),materials})},[scene,bones,boneByName,morphEntries,materials])
 useEffect(()=>{if(!selectedBoneName)return;const bone=boneByName[selectedBoneName];if(!bone)return;const d=Math.PI/180;bone.rotation.set((rotationDeg?.x||0)*d,(rotationDeg?.y||0)*d,(rotationDeg?.z||0)*d)},[boneByName,selectedBoneName,rotationDeg])
 useEffect(()=>{scene.traverse(o=>{if(!o.isMesh||!o.morphTargetDictionary||!o.morphTargetInfluences)return;for(const [name,index] of Object.entries(o.morphTargetDictionary))o.morphTargetInfluences[index]=Number(morphValues[name]??0)})},[scene,morphValues])
 useEffect(()=>{scene.traverse(o=>{if(!o.isMesh||!o.material)return;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{const cfg=materialConfig[m.uuid];if(!cfg)return;if(m.color&&cfg.color)m.color.set(cfg.color);if('roughness'in m&&cfg.roughness!=null)m.roughness=cfg.roughness;if('metalness'in m&&cfg.metalness!=null)m.metalness=cfg.metalness;m.needsUpdate=true})})},[scene,materialConfig])
 useFrame(()=>{if(!ikEnabled)return;for(const [targetKey,slots] of Object.entries(CHAINS)){const target=ikTargets[targetKey];if(!target)continue;const chain=slots.map(slot=>boneByName[mapping[slot]]).filter(Boolean);if(chain.length===3)solveCCD(chain,new THREE.Vector3(...target),4)}})
 return <group rotation={[0,exportYaw,0]}><primitive object={scene}/>{showBones&&bones.map(b=><Marker key={b.uuid} bone={b} active={b.name===selectedBoneName} onSelect={onSelectBone}/>) }{ikEnabled&&Object.entries(ikTargets).map(([name,pos])=><IKTarget key={name} name={name} position={pos} active={selectedIK===name} onSelect={onSelectIK}/>)}{assets.map(asset=>{const bone=boneByName[mapping[asset.socket]];return bone?<AttachedAsset key={asset.id} asset={asset} bone={bone}/>:null})}</group>
}
